# Variables
export ZSH="$HOME/.oh-my-zsh"
export ZSH_DISABLE_COMPFIX=true
export EDITOR='vim'

export PATH=$PATH:/opt/homebrew/bin
export PATH=$PATH:/usr/local/bin

export PATH=$PATH:/usr/local/share/android-commandlinetools/platform-tools
export PATH=$PATH:/usr/local/share/android-commandlinetools/emulator

export PATH=$PATH:$HOME/Tools/flutter/bin
export PATH=$PATH:$HOME/Tools/caddy
export PATH=$PATH:$HOME/.composer/vendor/bin
export PATH=/usr/local/opt/php@7.4/bin:$PATH
export PATH=$PATH:$HOME/.poetry/bin
export PATH="$HOME/.poetry/bin:$PATH"

export PNPM_HOME="/Users/jsarnowski/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"

export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"

export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"

# Theme
ZSH_THEME="common"

# Plugins
plugins=(
    git
    brew
    npm
    yarn
    nvm
    vscode
)

# Aliases
alias g='git'
alias lg='lazygit'

alias d='docker'
alias ld='lazydocker'
alias dc='docker-compose'
alias dp='docker system prune -f -a'

alias py='python3'
alias py2='python'
alias pip='pip3'
alias pip2='pip2'

alias n='npm'
alias p='pnpm'
alias y='yarn'
alias yw='yarn workspace'

# Z
. $(brew --prefix)/etc/profile.d/z.sh

# Added by NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"

# Added by Amplify CLI binary installer
export PATH="$HOME/.amplify/bin:$PATH"

# Lazygit
export LG_CONFIG_FILE="$HOME/.lazygit.yml"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Finalize
source "$ZSH/oh-my-zsh.sh"
source "${HOME}/.iterm2.zsh"