for conf in "$HOME/.config/zsh/"*.zsh; do
    source "${conf}"
done

unset conf

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# bun completions
[ -s "/Users/jsarnowski/.bun/_bun" ] && source "/Users/jsarnowski/.bun/_bun"
