# Variables
export ZSH="$HOME/.oh-my-zsh"
export ZSH_DISABLE_COMPFIX=true
export EDITOR='vim'

export PATH=$PATH:/usr/local/bin

export PATH=$PATH:/usr/local/share/android-commandlinetools/platform-tools
export PATH=$PATH:/usr/local/share/android-commandlinetools/emulator

export PATH=$PATH:$HOME/Tools/flutter/bin
export PATH=$PATH:$HOME/Tools/caddy
export PATH=$PATH:$HOME/.composer/vendor/bin
export PATH=/usr/local/opt/php@7.4/bin:$PATH

# Theme
ZSH_THEME="common"

# Plugins
plugins=(
    git
    brew
    npm
    yarn
    nvm
    vscode
)

# Aliases
alias g='git'

alias d='docker'
alias ld='lazydocker'
alias dc='docker-compose'
alias dp='docker system prune -f -a'

alias py='python3'
alias py2='python'
alias pip='pip3'
alias pip2='pip2'

# Z
. $(brew --prefix)/etc/profile.d/z.sh

# Finalize
source "$ZSH/oh-my-zsh.sh"
source "${HOME}/.iterm2.zsh"
